# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/digitalasset/daml/lf/archive/daml_lf.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'com/digitalasset/daml/lf/archive/daml_lf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.digitalasset.daml.lf.archive import daml_lf2_pb2 as com_dot_digitalasset_dot_daml_dot_lf_dot_archive_dot_daml__lf2__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.com/digitalasset/daml/lf/archive/daml_lf.proto\x12\x07\x64\x61ml_lf\x1a/com/digitalasset/daml/lf/archive/daml_lf2.proto\"m\n\x0e\x41rchivePayload\x12\r\n\x05minor\x18\x03 \x01(\t\x12\r\n\x05patch\x18\x05 \x01(\x05\x12\x13\n\tdaml_lf_1\x18\x02 \x01(\x0cH\x00\x12\x13\n\tdaml_lf_2\x18\x04 \x01(\x0cH\x00\x42\x05\n\x03SumJ\x06\x08\x8fN\x10\x90NJ\x04\x08\x01\x10\x02\"V\n\x07\x41rchive\x12,\n\rhash_function\x18\x01 \x01(\x0e\x32\x15.daml_lf.HashFunction\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x0c\n\x04hash\x18\x04 \x01(\t*\x1a\n\x0cHashFunction\x12\n\n\x06SHA256\x10\x00\x42L\n com.digitalasset.daml.lf.archive\xaa\x02\'Com.DigitalAsset.Daml.Lf.Archive.DamlLfb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.digitalasset.daml.lf.archive.daml_lf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.digitalasset.daml.lf.archive\252\002\'Com.DigitalAsset.Daml.Lf.Archive.DamlLf'
  _globals['_HASHFUNCTION']._serialized_start=307
  _globals['_HASHFUNCTION']._serialized_end=333
  _globals['_ARCHIVEPAYLOAD']._serialized_start=108
  _globals['_ARCHIVEPAYLOAD']._serialized_end=217
  _globals['_ARCHIVE']._serialized_start=219
  _globals['_ARCHIVE']._serialized_end=305
# @@protoc_insertion_point(module_scope)
